;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Slot.Equipment.Head",NewTagName="Slot.Equipment.Armor.Head")
+GameplayTagList=(Tag="Character.Action.AttackHitCheck",DevComment="")
+GameplayTagList=(Tag="Character.Interaction",DevComment="")
+GameplayTagList=(Tag="Character.Interaction.Enchant",DevComment="")
+GameplayTagList=(Tag="Character.Interaction.Quest",DevComment="")
+GameplayTagList=(Tag="Character.State.IsAttacking",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDamaged",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDead",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDrawing",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDrawn",DevComment="")
+GameplayTagList=(Tag="Character.State.IsJumping",DevComment="")
+GameplayTagList=(Tag="Character.State.IsSheathing",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.Attack",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Potion.Health",DevComment="소비/포션/체력포션")
+GameplayTagList=(Tag="Item.Consumable.Potion.Mana",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Upgrade",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Upgrade.Attack",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Upgrade.Health",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Chest",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Gloves",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Head",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Legs",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Shoes",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Shield",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapon.Sword",DevComment="장비/무기/검")
+GameplayTagList=(Tag="Monster.Action.DashAttack",DevComment="")
+GameplayTagList=(Tag="Monster.Action.DashStart",DevComment="")
+GameplayTagList=(Tag="Monster.Action.DoubleWaterBomb",DevComment="")
+GameplayTagList=(Tag="Monster.Action.EnergyBomb",DevComment="")
+GameplayTagList=(Tag="Monster.Action.Howling",DevComment="")
+GameplayTagList=(Tag="Monster.Action.LeftWingStomp",DevComment="보스 몬스터 LeftWingStomp 공격")
+GameplayTagList=(Tag="Slot.Consumable",DevComment="")
+GameplayTagList=(Tag="Slot.Equipment",DevComment="")
+GameplayTagList=(Tag="Slot.Equipment.Armor.Chest",DevComment="")
+GameplayTagList=(Tag="Slot.Equipment.Armor.Gloves",DevComment="")
+GameplayTagList=(Tag="Slot.Equipment.Armor.Head",DevComment="")
+GameplayTagList=(Tag="Slot.Equipment.Armor.Legs",DevComment="")
+GameplayTagList=(Tag="Slot.Equipment.Armor.Shoes",DevComment="")
+GameplayTagList=(Tag="Slot.Equipment.Weapon",DevComment="")

